### ISSUE TITLE
mac Chrome 49部分区域点击没反应

### ISSUE THREAD

**Issue by virusdefender** [firesunCN/BlueLotus_XSSReceiver#1]
主要是我的JS和JS模板，console没有发现JS错误

Safari都正常

**Comment by firesunCN** [comment]
能截图说明一下吗？是什么地方出了问题？

**Comment by virusdefender** [comment]
就是左侧的列表项啊，包括js列表，我的模板等。

**Comment by firesunCN** [comment]
这个是靠bootstrap跳转的，和后台还没关系，我找个mac看看

**Comment by virusdefender** [comment]
![qq20160321-0 2x](https://cloud.githubusercontent.com/assets/4939404/13910436/11173c1c-ef5d-11e5-83ec-76c11efc7cf7.png)
![qq20160321-1 2x](https://cloud.githubusercontent.com/assets/4939404/13910435/11148558-ef5d-11e5-8663-5435e7229733.png)

谢谢~

**Comment by virusdefender** [comment]
而且mac chrome下问题颇多，我尝试录屏给您看下。

**Comment by virusdefender** [comment]
链接: http://pan.baidu.com/s/1c0WcRra 密码: jeft

鼠标停留的部分都没办法点击，包括cookies列表，js列表、模板列表和modal关闭按钮等。

**Comment by firesunCN** [comment]
不好意思，终于有时间测试一下了，我用mac的Safari，chrome49（64bit）都测试过了，没有发现你所说的不能点击的问题，你重新clone一次再试试？看看是不是缺了什么js？

**Comment by virusdefender** [comment]
咦，奇怪。我console看不到任何报错信息。我找空自己debug一下。

十分感谢。

**Comment by firesunCN** [comment]
么事，我先close了
