### ISSUE TITLE
接收面板加载比较慢

### ISSUE THREAD

**Issue by baozhibo** [firesunCN/BlueLotus_XSSReceiver#2]
大概11个接收，接收面板加载时间大概超过1分钟。

**Comment by firesunCN** [comment]
是否是因为你收到的11个接收都很大，带着很长的post？如果不是的话应该是你的网络慢导致的，受限于ui，目前所有的xss数据都是一次性加载的

**Comment by baozhibo** [comment]
是因为长POST，谢谢回复

2016-05-14 1:17 GMT+08:00 火日攻天@firesun <notifications@github.com>:

**Comment by firesunCN** [comment]
恩 好的那我先close了
