### ISSUE TITLE
新安装有个bug，什么都不操作直接点下一步。登录就会提示密码错误

### ISSUE THREAD

**Issue by baozhibo** [firesunCN/BlueLotus_XSSReceiver#3]
新安装。给文件夹写权限后，页面密码不修改，直接下一步，登录依然提示密码错误。

**Comment by baozhibo** [comment]
手动安装也是一样。输入默认密码即提示密码错误

**Comment by firesunCN** [comment]
我觉得是你的浏览器没执行js吧

**Comment by baozhibo** [comment]
mac 10.11.5  换了用了 chorme   ff  safari 三个结果都一样。。＝ ＝就差跑去用ie了

2016-06-16 18:21 GMT+08:00 火日攻天@firesun <notifications@github.com>:

**Comment by firesunCN** [comment]
没复现出问题，建议f12观察下js执行了没，可能是js就没加载

**Comment by loseyourself1** [comment]
> 
你好，我也出现了这个问题，请问是如何解决的呢？

**Comment by Ca1mD** [comment]
Demon已经收到您的邮件，谢谢您。
