### ISSUE TITLE
关于类SAE系统部署问题

### ISSUE THREAD

**Issue by BackTrackCRoot** [firesunCN/BlueLotus_XSSReceiver#4]
我将该平台部署在国外某APP开发平台，会出现登录后自动登出问题。经查猜测是Auth.php中的IP检查所致，然后导致异常登出。所以希望能够修复一下~Thanks

> 时间
> IP
> 来源
> 客户端
> 请求
> 携带数据
> 保持连接
> 2016年10月16日 10:56:59
> 10.10.129.29
> 局域网
> Windows NT Chrome(53.0.2785.89)
> GET
> {"GET":["get"],"COOKIE":["PHPSESSID"]}
> 否

**Comment by firesunCN** [comment]
我抽空加一个选项来解决这个问题，还是尽量不要相信XFF的内容

**Comment by BackTrackCRoot** [comment]
确实，当初我在加代码的时候就有点犹豫了，如果这个平台是在开发者APP上的XFF内容是没有问题的一般，但是如果是在独立服务器上部署，可能就有些问题了。感谢~

**Comment by firesunCN** [comment]
已commit，增加了两个选项，可以选择是否校验ip以及是否使用xff来作为源ip，你也可以试试，我先关闭issue了

**Comment by BackTrackCRoot** [comment]
感谢~~
