### ISSUE TITLE
收不到cookie

### ISSUE THREAD

**Issue by lewisec** [firesunCN/BlueLotus_XSSReceiver#6]
ubuntu16.04的vps，装好apache和php5，页面可以访问，只修改了登录密码。
新建一个js模板，插入alert.js，本机新建一个html文件，插入http://1X.X.X.X/xss/myjs/test.js，浏览器打开这个html，可以弹窗。
再新建一个js模板，插入default.js，生成js，虚拟机上装有dvwa，在里面插入js，再回到vps访问接收面板，没有数据。vps上去访问data目录，只有.htaccess/forbiddenIPList.dat/index.html三个文件。
是我哪里配置错了吗？

**Comment by lewisec** [comment]
找到原因了。
在默认模板中，有一句：var website = "http://网站地址";
我把平台代码解压缩到了vps的apache目录的xss子目录下，这句需要修改成http://1.1.1.1/xss，之前没有加子目录，所以一直收不到信。
感谢作者无私奉献。

**Comment by firesunCN** [comment]
嗯 模板只是给一个参考，需要自己修改
