### ISSUE TITLE
xss接收面板空白

### ISSUE THREAD

**Issue by opswill** [firesunCN/BlueLotus_XSSReceiver#7]
服务器环境： FreeBSD11.0 + Nginx + PHP56
PHP模块：

    Core
    ctype
    curl
    date
    ereg
    fileinfo
    json
    libxml
    mbstring
    mysql
    mysqlnd
    openssl
    pcre
    PDO
    pdo_mysql
    redis
    Reflection
    session
    SPL
    standard
    tokenizer
    Zend OPcache
测试浏览器: windows 10 64 位 102400 ， chrome  56.0.2924.87(64-bit),firefox 51.0.1 (32 位)
问题：配置了邮件提醒，能收到cookies邮件提醒，但是cookies接收面板始终空白，测试多次都是空白
附上Firebug和chrome console的截图：
![chrome](https://cloud.githubusercontent.com/assets/7550211/22933604/04888e48-f307-11e6-9c16-912a9512d6bb.png)
![firefox](https://cloud.githubusercontent.com/assets/7550211/22933608/096c73a2-f307-11e6-924b-268cb24a11bc.png)
麻烦帮忙定位下，感谢

**Comment by firesunCN** [comment]
访问/api.php?cmd=list看看，截个图

**Comment by willis55** [comment]
/api.php?cmd=list 是空的，控制台没有错误，但是data下是有生成文件的
![data](https://cloud.githubusercontent.com/assets/7550211/23092565/be11108e-f608-11e6-8045-e72878c4aff4.png)

**Comment by willis55** [comment]
第一张图里的error,我通过改CSP修复了
//开启CSP
header("Content-Security-Policy: default-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; frame-src 'none';script-src 'self' 'unsafe-inline'");

**Comment by firesunCN** [comment]
按理说是没有内联的script的，如果能粘贴下是哪段代码报错的么

**Comment by Ca1mD** [comment]
Demon已经收到您的邮件，谢谢您。
